=== BernhardWerth/ROAR-NET-problem-statements/problems/salt-spreading/support/schema_instance.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "max_time": {
      "type": "number"
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "position": {
            "type": "array",
            "items": {
              "type": ["null","number"]
            }
          }
        },
        "required": [
          "label",
          "position"
        ]
      }
    },
    "vehicles": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "home": {
            "type": "string"
          },
          "capacity": {
            "type": "number"
          }
        },
        "required": [
          "capacity",
          "home",
          "id"
        ]
      }
    },
    "depots": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "refill": {
            "type": "number"
          }
        },
        "required": [
          "label",
          "refill"
        ]
      }
    },
    "A": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "arc": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "len": {
            "type": "number"
          },
          "time": {
            "type": "number"
          }
        },
        "required": [
          "arc",
          "len",
          "time"
        ]
      }
    },
    "A_R": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "arc": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "dem": {
            "type": "number"
          },
          "len": {
            "type": "number"
          },
          "time": {
            "type": "number"
          }
        },
        "required": [
          "arc",
          "dem",
          "len",
          "time"
        ]
      }
    },
    "E_R": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "edge": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "dem": {
            "type": "number"
          },
          "len": {
            "type": "number"
          },
          "time": {
            "type": "number"
          }
        },
        "required": [
          "dem",
          "edge",
          "len",
          "time"
        ]
      }
    },
    "U": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          }
        },
        "required": [
          "label"
        ]
      }
    }
  },
  "required": [
    "A",
    "A_R",
    "E_R",
    "U",
    "depots",
    "max_time",
    "name",
    "nodes",
    "vehicles"
  ]
}

=== BernhardWerth/ROAR-NET-problem-statements/problems/salt-spreading/data/belben/belben.json
{
    "name": "BelBen",
    "max_time": 100000,
    "nodes": [
        {
            "label": "1",
            "position": [
                10,
                50
            ]
        },
        {
            "label": "2",
            "position": [
                20,
                90
            ]
        },
        {
            "label": "3",
            "position": [
                20,
                60
            ]
        },
        {
            "label": "4",
            "position": [
                20,
                40
            ]
        },
        {
            "label": "5",
            "position": [
                20,
                10
            ]
        },
        {
            "label": "6",
            "position": [
                30,
                60
            ]
        },
        {
            "label": "7",
            "position": [
                30,
                40
            ]
        }
    ],
    "vehicles": [
        {
            "id": "1",
            "home": "1",
            "capacity": 25.0
        },
        {
            "id": "2",
            "home": "1",
            "capacity": 25.0
        }
    ],
    "depots": [{"label": "1", "refill": 25.0}],
    "A": [
        {
            "arc": [
                "4",
                "7"
            ],
            "time": 0,
            "len": 1
        },
        {
            "arc": [
                "7",
                "4"
            ],
            "time": 0,
            "len": 1
        }
    ],
    "A_R": [],
    "E_R": [
        {
            "edge": [
                "1",
                "2"
            ],
            "time": 0,
            "len": 1,
            "dem": 3
        },
        {
            "edge": [
                "1",
                "3"
            ],
            "time": 0,
            "len": 1,
            "dem": 4
        },
        {
            "edge": [
                "1",
                "4"
            ],
            "time": 0,
            "len": 1,
            "dem": 4
        },
        {
            "edge": [
                "1",
                "5"
            ],
            "time": 0,
            "len": 1,
            "dem": 3
        },
        {
            "edge": [
                "2",
                "3"
            ],
            "time": 0,
            "len": 1,
            "dem": 1
        },
        {
            "edge": [
                "3",
                "4"
            ],
            "time": 0,
            "len": 1,
            "dem": 1
        },
        {
            "edge": [
                "3",
                "6"
            ],
            "time": 0,
            "len": 1,
            "dem": 5
        },
        {
            "edge": [
                "4",
                "5"
            ],
            "time": 0,
            "len": 1,
            "dem": 1
        },
        {
            "edge": [
                "6",
                "7"
            ],
            "time": 0,
            "len": 1,
            "dem": 14
        }
    ],
    "U": []
}

=== BernhardWerth/ROAR-NET-problem-statements/problems/salt-spreading/data/gualandi/gualandi.json
{
    "name": "Gualandi",
    "max_time": 100000,
    "nodes": [
        {
            "label": "0",
            "position": [
                0,
                12
            ]
        },
        {
            "label": "1",
            "position": [
                4,
                8
            ]
        },
        {
            "label": "2",
            "position": [
                12,
                8
            ]
        },
        {
            "label": "3",
            "position": [
                4,
                3
            ]
        },
        {
            "label": "4",
            "position": [
                12,
                3
            ]
        },
        {
            "label": "5",
            "position": [
                17,
                12
            ]
        },
        {
            "label": "6",
            "position": [
                17,
                17
            ]
        },
        {
            "label": "7",
            "position": [
                20,
                3
            ]
        }
    ],
    "vehicles": [
        {
            "id": "1",
            "home": "0",
            "capacity": 50.0
        }
    ],
    "depots": [
        {
            "label": "7",
            "refill": 50.0
        }
    ],
    "A": [
        {
            "arc": [
                "0",
                "1"
            ],
            "time": 0,
            "len": 6
        },
        {
            "arc": [
                "2",
                "3"
            ],
            "time": 0,
            "len": 10
        },
        {
            "arc": [
                "2",
                "4"
            ],
            "time": 0,
            "len": 5
        },
        {
            "arc": [
                "2",
                "5"
            ],
            "time": 0,
            "len": 7
        },
        {
            "arc": [
                "1",
                "3"
            ],
            "time": 0,
            "len": 5
        },
        {
            "arc": [
                "4",
                "7"
            ],
            "time": 0,
            "len": 8
        },
        {
            "arc": [
                "5",
                "7"
            ],
            "time": 0,
            "len": 10
        },
        {
            "arc": [
                "1",
                "0"
            ],
            "time": 0,
            "len": 6
        },
        {
            "arc": [
                "3",
                "2"
            ],
            "time": 0,
            "len": 10
        },
        {
            "arc": [
                "4",
                "2"
            ],
            "time": 0,
            "len": 5
        },
        {
            "arc": [
                "5",
                "2"
            ],
            "time": 0,
            "len": 7
        },
        {
            "arc": [
                "3",
                "1"
            ],
            "time": 0,
            "len": 5
        },
        {
            "arc": [
                "7",
                "4"
            ],
            "time": 0,
            "len": 8
        },
        {
            "arc": [
                "7",
                "5"
            ],
            "time": 0,
            "len": 10
        },
        {
            "arc": [
                "5",
                "6"
            ],
            "time": 0,
            "len": 5
        },
        {
            "arc": [
                "4",
                "3"
            ],
            "time": 0,
            "len": 8
        }
    ],
    "A_R": [
        {
            "arc": [
                "3",
                "4"
            ],
            "time": 0,
            "len": 8,
            "dem": 20
        },
        {
            "arc": [
                "6",
                "5"
            ],
            "time": 0,
            "len": 5,
            "dem": 30
        }
    ],
    "E_R": [
        {
            "edge": [
                "1",
                "2"
            ],
            "time": 0,
            "len": 8,
            "dem": 30
        }
    ],
    "U": [
        {
            "label": "0"
        },
        {
            "label": "6"
        }
    ]
}
